### ISSUE TITLE
Problèmes la struct eventName

### ISSUE THREAD

**Issue by lexinor** [SUP2Ak/sup2ak.github.io#1]
Salut !

En mettant en place les modifications qu'il faut faire dans esx_society, je suis tombé sur un problème avec le nom des events. Il manque le préfix "esx_society:" aux noms des events. A voir comment l'intégrer, j'ai simplement fait ça de mon côté mais a voir si tu veux l'intégrer d'une autre manière.

```
local eventName <const> = {
    ['job'] = {
        set = 'esx_society:setJob',
        get = 'esx_society:getJob',
        label = 'esx_society:setJobLabel',
        salary = 'esx_society:setJobSalary',
    },

    ['faction'] = {
        set = 'esx_society:setFaction',
        get = 'esx_society:getFaction',
        label = 'esx_society:setFactionLabel',
        salary = 'esx_society:setFactionSalary',
    }
}
```

PS : Je voulais faire une PR mais impossible donc je fais une issue :)

**Comment by SUP2Ak** [comment]
La structure de la documentation, n'est pas la même que la template d'où ton erreur
